### PR TITLE
Add support for track rating

### PR DESCRIPTION
**Pull request by rosenfeld**
I've fixed some minor bugs and added support for track rating in my repository.

Please, take a look and let me know how it looks in iPhone, as I only own an Android.

Thanks for your work, by the way! :)

### CODE REVIEW

**Comment by jwchile** [comment]
Hi Rodrigo,

unfortunately I don't have time anymore to maintain this project. Would you
be interested in taking over? I'd give you write access to the repository.

Cheers,
Johannes

On Tue, Feb 14, 2012 at 5:32 PM, Rodrigo Rosenfeld Rosas <
reply@reply.github.com

**Comment by rosenfeld** [comment]
Would I be allowed to do a complete refactoring on it? If so, yes, I'd like to maintain it :)

**Comment by jwchile** [comment]
On Wed, Feb 15, 2012 at 2:38 AM, Rodrigo Rosenfeld Rosas <
reply@reply.github.com

> wrote:
> 
> Would I be allowed to do a complete refactoring on it? If so, yes, I'd
> like to maintain it :)

Sure, go crazy with it :) This was my first and so far last experiment with
JavaScript and I mostly stopped using Amarok. I'm happy if the project
lives on.

I just added you as a collaborator in the github repo. Is that sufficient
(haven't used github much so far).

Cheers,
Johannes

**Comment by rosenfeld** [comment]
Yes, thanks! :)

**Pull request merged**
